### ISSUE TITLE
inetmanet-2.0 compilation error on OMNET++ 4.5

### ISSUE THREAD

**Issue by seemakumar8** [aarizaq/inetmanet-3.x#21]
Dear aarizaq,

When I try to build internet-2.0 on OMNET++ 4.5, I get the following error:
"variable length array of non-POD element type 'MACAddress'" in file hwmp.cc at line 1670

Is the issue with the version?

Thanks,

**Comment by aarizaq** [comment]
I can’t reproduce the problem. I have just compile the framework with omnet 4.6 without problems

De: seemakumar8 [mailto:notifications@github.com] 
Enviado el: domingo, 02 de noviembre de 2014 0:13
Para: aarizaq/inetmanet-2.0
Asunto: [inetmanet-2.0] inetmanet-2.0 compilation error on OMNET++ 4.5 (#21)

Dear aarizaq,

When I try to build internet-2.0 on OMNET++ 4.5, I get the following error:
"variable length array of non-POD element type 'MACAddress'" in file hwmp.cc at line 1670

Is the issue with the version?

Thanks,
